USE [master]
GO

/****** Object:  Database [NewUsuario]    Script Date: 10/01/2023 20:39:22 ******/
CREATE DATABASE [NewUsuario]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NewUsuario', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\NewUsuario.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NewUsuario_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\NewUsuario_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NewUsuario].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NewUsuario] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NewUsuario] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NewUsuario] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NewUsuario] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NewUsuario] SET ARITHABORT OFF 
GO

ALTER DATABASE [NewUsuario] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [NewUsuario] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NewUsuario] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NewUsuario] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NewUsuario] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NewUsuario] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NewUsuario] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NewUsuario] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NewUsuario] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NewUsuario] SET  ENABLE_BROKER 
GO

ALTER DATABASE [NewUsuario] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NewUsuario] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NewUsuario] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NewUsuario] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NewUsuario] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NewUsuario] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [NewUsuario] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NewUsuario] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [NewUsuario] SET  MULTI_USER 
GO

ALTER DATABASE [NewUsuario] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NewUsuario] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NewUsuario] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NewUsuario] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NewUsuario] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NewUsuario] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [NewUsuario] SET QUERY_STORE = OFF
GO

ALTER DATABASE [NewUsuario] SET  READ_WRITE 
GO

